name = "pill-tracker"
compatibility_date = "2025-06-01"

pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "pill-tracker-db"
database_id = "2b9b37fc-2326-4ea5-984c-dad2574ee181"
